# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ina_frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ina_frontend
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]


  target 'ina_frontend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ina_frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ina_frontend-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ina_frontend-tvOS

 
end
